### ISSUE TITLE
Error when installing from github

### ISSUE THREAD

**Issue by mahermassoud** [icbi-lab/immunedeconv#44] opened 2020-05-01 03:54 UTC
When I install from github using devtools or remote, I get the following error

```
> library(immunedeconv)
Loading required package: EPIC
Error: package or namespace load failed for ‘immunedeconv’ in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]):
 namespace ‘BiocGenerics’ 0.30.0 is being loaded, but >= 0.31.2 is required
```

So I try to updaate `BiocGenerics` and get the following:

```
> BiocManager::install("BiocGenerics")
Bioconductor version 3.9 (BiocManager 1.30.10), R 3.6.0 (2019-04-26)
Installing package(s) 'BiocGenerics'
trying URL 'https://bioconductor.org/packages/3.9/bioc/bin/macosx/el-capitan/contrib/3.6/BiocGenerics_0.30.0.tgz'
Content type 'application/x-gzip' length 637480 bytes (622 KB)
==================================================
downloaded 622 KB


The downloaded binary packages are in
	/var/folders/9m/dy7kzyp50fldn0ydz_9wj8180000gn/T//RtmpkZpJCh/downloaded_packages
Old packages: 'DescTools'
Update all/some/none? [a/s/n]: a

  There is a binary version available but the source version is later:
           binary  source needs_compilation
DescTools 0.99.34 0.99.35              TRUE

Do you want to install from sources the package which needs compilation? (Yes/no/cancel) Yes
installing the source package ‘DescTools’

trying URL 'https://cran.rstudio.com/src/contrib/DescTools_0.99.35.tar.gz'
Content type 'application/x-gzip' length 2476177 bytes (2.4 MB)
==================================================
downloaded 2.4 MB

* installing *source* package ‘DescTools’ ...
** package ‘DescTools’ successfully unpacked and MD5 sums checked
** using staged installation
** libs
clang -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG  -I"/Library/Frameworks/R.framework/Versions/3.6/Resources/library/Rcpp/include" -I"/Library/Frameworks/R.framework/Versions/3.6/Resources/library/BH/include" -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -I/usr/local/include  -fPIC  -Wall -g -O2  -c ADinf.c -o ADinf.o
clang -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG  -I"/Library/Frameworks/R.framework/Versions/3.6/Resources/library/Rcpp/include" -I"/Library/Frameworks/R.framework/Versions/3.6/Resources/library/BH/include" -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -I/usr/local/include  -fPIC  -Wall -g -O2  -c AnDarl.c -o AnDarl.o
clang -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG  -I"/Library/Frameworks/R.framework/Versions/3.6/Resources/library/Rcpp/include" -I"/Library/Frameworks/R.framework/Versions/3.6/Resources/library/BH/include" -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -I/usr/local/include  -fPIC  -Wall -g -O2  -c Barnard.c -o Barnard.o
clang++ -std=gnu++11 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG  -I"/Library/Frameworks/R.framework/Versions/3.6/Resources/library/Rcpp/include" -I"/Library/Frameworks/R.framework/Versions/3.6/Resources/library/BH/include" -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -I/usr/local/include  -fPIC  -Wall -g -O2  -c RcppExports.cpp -o RcppExports.o
clang++ -std=gnu++11 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG  -I"/Library/Frameworks/R.framework/Versions/3.6/Resources/library/Rcpp/include" -I"/Library/Frameworks/R.framework/Versions/3.6/Resources/library/BH/include" -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -I/usr/local/include  -fPIC  -Wall -g -O2  -c aux_fct.cpp -o aux_fct.o
clang -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG  -I"/Library/Frameworks/R.framework/Versions/3.6/Resources/library/Rcpp/include" -I"/Library/Frameworks/R.framework/Versions/3.6/Resources/library/BH/include" -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -I/usr/local/include  -fPIC  -Wall -g -O2  -c between.c -o between.o
gfortran  -fPIC  -Wall -g -O2  -c cidxcn.f -o cidxcn.o
cidxcn.f:70:5:

   70 | 23003 continue
      |     1
Warning: Label 23003 at (1) defined but not used [-Wunused-label]
cidxcn.f:77:5:

   77 | 23001 continue
      |     1
Warning: Label 23001 at (1) defined but not used [-Wunused-label]
clang -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG  -I"/Library/Frameworks/R.framework/Versions/3.6/Resources/library/Rcpp/include" -I"/Library/Frameworks/R.framework/Versions/3.6/Resources/library/BH/include" -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -I/usr/local/include  -fPIC  -Wall -g -O2  -c conc.c -o conc.o
clang -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG  -I"/Library/Frameworks/R.framework/Versions/3.6/Resources/library/Rcpp/include" -I"/Library/Frameworks/R.framework/Versions/3.6/Resources/library/BH/include" -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -I/usr/local/include  -fPIC  -Wall -g -O2  -c exactsum.c -o exactsum.o
clang++ -std=gnu++11 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG  -I"/Library/Frameworks/R.framework/Versions/3.6/Resources/library/Rcpp/include" -I"/Library/Frameworks/R.framework/Versions/3.6/Resources/library/BH/include" -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -I/usr/local/include  -fPIC  -Wall -g -O2  -c extremes.cpp -o extremes.o
clang -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG  -I"/Library/Frameworks/R.framework/Versions/3.6/Resources/library/Rcpp/include" -I"/Library/Frameworks/R.framework/Versions/3.6/Resources/library/BH/include" -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -I/usr/local/include  -fPIC  -Wall -g -O2  -c fdwilcox.c -o fdwilcox.o
clang -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG  -I"/Library/Frameworks/R.framework/Versions/3.6/Resources/library/Rcpp/include" -I"/Library/Frameworks/R.framework/Versions/3.6/Resources/library/BH/include" -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -I/usr/local/include  -fPIC  -Wall -g -O2  -c fpow.c -o fpow.o
clang++ -std=gnu++11 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG  -I"/Library/Frameworks/R.framework/Versions/3.6/Resources/library/Rcpp/include" -I"/Library/Frameworks/R.framework/Versions/3.6/Resources/library/BH/include" -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -I/usr/local/include  -fPIC  -Wall -g -O2  -c gompertz.cpp -o gompertz.o
gfortran  -fPIC  -Wall -g -O2  -c hoeffd.f -o hoeffd.o
hoeffd.f:50:5:

   50 | 23017 continue
      |     1
Warning: Label 23017 at (1) defined but not used [-Wunused-label]
hoeffd.f:52:5:

   52 | 23015 continue
      |     1
Warning: Label 23015 at (1) defined but not used [-Wunused-label]
hoeffd.f:28:5:

   28 | 23009 continue
      |     1
Warning: Label 23009 at (1) defined but not used [-Wunused-label]
hoeffd.f:39:5:

   39 | 23007 continue
      |     1
Warning: Label 23007 at (1) defined but not used [-Wunused-label]
hoeffd.f:15:5:

   15 | 23003 continue
      |     1
Warning: Label 23003 at (1) defined but not used [-Wunused-label]
hoeffd.f:41:5:

   41 | 23001 continue
      |     1
Warning: Label 23001 at (1) defined but not used [-Wunused-label]
hoeffd.f:76:5:

   76 | 23019 continue
      |     1
Warning: Label 23019 at (1) defined but not used [-Wunused-label]
hoeffd.f:113:5:

  113 | 23023 continue
      |     1
Warning: Label 23023 at (1) defined but not used [-Wunused-label]
hoeffd.f:118:5:

  118 | 23021 continue
      |     1
Warning: Label 23021 at (1) defined but not used [-Wunused-label]
clang -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG  -I"/Library/Frameworks/R.framework/Versions/3.6/Resources/library/Rcpp/include" -I"/Library/Frameworks/R.framework/Versions/3.6/Resources/library/BH/include" -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -I/usr/local/include  -fPIC  -Wall -g -O2  -c init.c -o init.o
gfortran  -fPIC  -Wall -g -O2  -c jtpdf.f -o jtpdf.o
clang -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG  -I"/Library/Frameworks/R.framework/Versions/3.6/Resources/library/Rcpp/include" -I"/Library/Frameworks/R.framework/Versions/3.6/Resources/library/BH/include" -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -I/usr/local/include  -fPIC  -Wall -g -O2  -c ks.c -o ks.o
clang -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG  -I"/Library/Frameworks/R.framework/Versions/3.6/Resources/library/Rcpp/include" -I"/Library/Frameworks/R.framework/Versions/3.6/Resources/library/BH/include" -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -I/usr/local/include  -fPIC  -Wall -g -O2  -c moments.c -o moments.o
gfortran  -fPIC  -Wall -g -O2  -c pan.f -o pan.o
clang -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG  -I"/Library/Frameworks/R.framework/Versions/3.6/Resources/library/Rcpp/include" -I"/Library/Frameworks/R.framework/Versions/3.6/Resources/library/BH/include" -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -I/usr/local/include  -fPIC  -Wall -g -O2  -c pointinpolygon.c -o pointinpolygon.o
clang -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG  -I"/Library/Frameworks/R.framework/Versions/3.6/Resources/library/Rcpp/include" -I"/Library/Frameworks/R.framework/Versions/3.6/Resources/library/BH/include" -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -I/usr/local/include  -fPIC  -Wall -g -O2  -c ranksort.c -o ranksort.o
clang -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG  -I"/Library/Frameworks/R.framework/Versions/3.6/Resources/library/Rcpp/include" -I"/Library/Frameworks/R.framework/Versions/3.6/Resources/library/BH/include" -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -I/usr/local/include  -fPIC  -Wall -g -O2  -c roman2int.c -o roman2int.o
clang -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG  -I"/Library/Frameworks/R.framework/Versions/3.6/Resources/library/Rcpp/include" -I"/Library/Frameworks/R.framework/Versions/3.6/Resources/library/BH/include" -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -I/usr/local/include  -fPIC  -Wall -g -O2  -c tbrm.c -o tbrm.o
clang -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG  -I"/Library/Frameworks/R.framework/Versions/3.6/Resources/library/Rcpp/include" -I"/Library/Frameworks/R.framework/Versions/3.6/Resources/library/BH/include" -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -I/usr/local/include  -fPIC  -Wall -g -O2  -c wgt_himed.c -o wgt_himed.o
clang++ -std=gnu++11 -dynamiclib -Wl,-headerpad_max_install_names -undefined dynamic_lookup -single_module -multiply_defined suppress -L/Library/Frameworks/R.framework/Resources/lib -L/usr/local/lib -o DescTools.so ADinf.o AnDarl.o Barnard.o RcppExports.o aux_fct.o between.o cidxcn.o conc.o exactsum.o extremes.o fdwilcox.o fpow.o gompertz.o hoeffd.o init.o jtpdf.o ks.o moments.o pan.o pointinpolygon.o ranksort.o roman2int.o tbrm.o wgt_himed.o -L/usr/local/gfortran/lib/gcc/x86_64-apple-darwin15/6.1.0 -L/usr/local/gfortran/lib -lgfortran -lquadmath -lm -F/Library/Frameworks/R.framework/.. -framework R -Wl,-framework -Wl,CoreFoundation
ld: warning: directory not found for option '-L/usr/local/gfortran/lib/gcc/x86_64-apple-darwin15/6.1.0'
ld: warning: directory not found for option '-L/usr/local/gfortran/lib'
ld: library not found for -lgfortran
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [DescTools.so] Error 1
ERROR: compilation failed for package ‘DescTools’
* removing ‘/Users/massoudmaher/Library/R/3.6/library/DescTools’
* restoring previous ‘/Users/massoudmaher/Library/R/3.6/library/DescTools’

The downloaded source packages are in
	‘/private/var/folders/9m/dy7kzyp50fldn0ydz_9wj8180000gn/T/RtmpkZpJCh/downloaded_packages’
Warning message:
In install.packages(update[instlib == l, "Package"], l, repos = repos,  :
  installation of package ‘DescTools’ had non-zero exit status
```

```
> sessionInfo()
R version 3.6.0 (2019-04-26)
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: macOS Mojave 10.14.3

Matrix products: default
BLAS:   /Library/Frameworks/R.framework/Versions/3.6/Resources/lib/libRblas.0.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/3.6/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base

other attached packages:
[1] EPIC_1.1.5

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.4.6          magrittr_1.5          hms_0.5.3
 [4] MASS_7.3-51.6         tidyselect_1.0.0      BiocParallel_1.20.1
 [7] R6_2.4.1              rlang_0.4.5           quadprog_1.5-8
[10] dplyr_0.8.5           parallel_3.6.0        lpSolve_5.6.15
[13] ellipsis_0.3.0        assertthat_0.2.1      tibble_3.0.1
[16] preprocessCore_1.48.0 lifecycle_0.2.0       crayon_1.3.4
[19] purrr_0.3.4           readr_1.3.1           vctrs_0.2.4
[22] glue_1.4.0            compiler_3.6.0        pillar_1.4.3
[25] limSolve_1.5.6        pkgconfig_2.0.3
```

**Comment by grst** [comment] 2020-05-02 08:52
Hi @mahermassoud,

thanks for reporting! 
The failure to install `DescTools` seems independent of the upgrade of `BiocGenerics`. 
Can you try to select `Upgrade none [n]` when updating `BiocGenerics`? It should still do the upgrade but not attempt to update any other packages. 

In any case, the proper version of `BiocGenerics` should automatically be installed, which will be fixed in #45. 

Cheers, 
Gregor

**Comment by mahermassoud** [comment] 2020-05-03 23:33
Tried and it didn't work. I also tried to pull from #45 and install from source and that didn't work either. All got me the same error. I even deleted the `BiocGenerics` line from `DESCRIPTION` and got the same error. I am able to install on a linux machine but I'd like to be able to do it on mac.

**Comment by DarioS** [comment] 2020-05-04 01:00
Have you considered installing R version 4 and getting the latest version of all Bioconductor packages? Even if you do not have administrator privileges, compiling R from source and installing it to a personal directory is not difficult (relative to most bioinformatics software). You'll have a lot less problems with Bioconductor packages in future if you do that now.

**Comment by grst** [comment] 2020-05-04 06:51
Thanks for investigating! I'll set-up github actions to run the CI also on macos - If this is really a mac-related problem, I'll hopefully find the problem that way. 

Regarding R 4.0: I'm not sure if immunedeconv is compatible already...

**Comment by grst** [comment] 2020-05-05 17:51
With the latest update of xCell, immunedeconv should work on R4.0.0. 

I cannot reproduce the issue on the macOS CI. 

It could be worth trying with a clean R environment. Either
 * delete the folder where your packages got installed to (`r .libPaths()` or
 * create a fresh conda environment with just R and `remotes` installed: `conda create -c conda-forge -n R361 r-base=3.6.1 r-remotes`

**Comment by mahermassoud** [comment] 2020-05-05 17:58
I ended up making a Ubuntu docker container to run it which I put here (package is installed in this image):
https://hub.docker.com/r/mahermassoud/immunedeconv/tags

When I follow the conda environment instructions posted on the repo, I get a different error:
https://github.com/icbi-lab/immunedeconv/issues/37#issuecomment-622235156

Thanks for your help. I will be sticking to the docker container for now. Will let you know if I try out the things you mentioned.

**Comment by mahermassoud** [comment] 2020-05-13 18:06
Updating to R v4 fixed this

**Comment by grst** [comment] 2020-05-14 06:37
ok, great!

**Closed by grst** 2020-05-14 06:37 UTC
